#!/bin/bash

while [ ! "$(docker ps -q -f name=trabalho-sqlge)" ]
do
    echo "waiting java container start";
    sleep 5;
done;

while [ "$( docker container inspect -f '{{.State.Running}}' trabalho-sqlge )" == "true" ]
do
    echo "wait finish importation of data";
    sleep 5;
done;

GENERATE_SCRIPT_PATH=`realpath scripts/generate-n-export-bak-of-db`;

sudo sh -c "sudo chmod +x $GENERATE_SCRIPT_PATH";

sudo sh -c "$GENERATE_SCRIPT_PATH";